---
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "skyethepinkcat"
    groups:
      gh-actions-updates:
        patterns:
          - "*"

  - package-ecosystem: "nix"
    directory: "/"
    target-branch: develop
    schedule:
      interval: "weekly"
    assignees:
      - "skyethepinkcat"
    groups:
      flake-updates:
        patterns:
          - "*"
