name: Check formatting

on:
  push:
  pull_request:

jobs:
  nixfmt:
    name: nixfmt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Check Nix formatting
        run: nix fmt -- --check
